# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20160506_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '\u7528\u6237\u8868', 'verbose_name_plural': '\u7528\u6237\u8868'},
        ),
    ]
